devices:
  - name: "strih-snv"
    ip: "10.77.9.202"
    expected_speed: "10Gbps"

  - name: "stream-snv"
    ip: "10.77.9.204"
    expected_speed: "1Gbps"

  - name: "mbc-snv"
    ip: "10.77.9.232"
    expected_speed: "1Gbps"

  - name: "fohabl-snv"
    ip: "10.77.9.230"
    expected_speed: "2.5Gbps"

  - name: "iem-snv"
    ip: "10.77.9.231"
    expected_speed: "2.5Gbps"

  - name: "iem-dante"
    ip: "10.77.9.228"
    expected_speed: "1Gbps"

  - name: "tascam"
    ip: "10.77.9.229"
    expected_speed: "1Gbps"

  - name: "songs-snv"
    ip: "10.77.9.212"
    expected_speed: "1Gbps"

  - name: "resolume-snv"
    ip: "10.77.9.201"
    expected_speed: "2.5Gbps"

  - name: "cam1"
    ip: "cam1.lan"
    expected_speed: "1Gbps"

  - name: "cam2"
    ip: "cam2.lan"
    expected_speed: "1Gbps"

  - name: "cam3"
    ip: "cam3.lan"
    expected_speed: "1Gbps"

  - name: "cam4"
    ip: "cam4.lan"
    expected_speed: "1Gbps"

  - name: "propresenter-snv"
    ip: "10.77.9.203"
    expected_speed: "1Gbps"

  - name: "companion-snv"
    ip: "10.77.9.205"
    expected_speed: "1Gbps"

  - name: "artnet-snv"
    ip: "10.77.9.220"
    expected_speed: "10Mbps"
    mac: "28:FE:99:29:18:35"

  - name: "sluchatka-zvukar"
    ip: "10.77.9.227"
    expected_speed: "100Mbps"

  - name: "sd1"
    ip: "10.77.9.31"
    expected_speed: "1Gbps"

  - name: "sd2"
    ip: "10.77.9.32"
    expected_speed: "1Gbps"

  - name: "sd3"
    ip: "10.77.9.33"
    expected_speed: "1Gbps"

  - name: "sd4"
    ip: "10.77.9.34"
    expected_speed: "1Gbps"
