devices:
  - name: "strih-snv"
    ip: "10.77.9.202"
    expected_speed: "10Gbps"

  - name: "stream-snv"
    ip: "10.77.9.204"
    expected_speed: "1Gbps"

  - name: "mbc-snv"
    ip: "10.77.9.232"
    expected_speed: "1Gbps"
